#!/bin/bash
# =============================================================================
# setup_binlog.sh
# Configures and enables MariaDB binary logging for Point-in-Time Recovery
# Supported systems: Debian / Ubuntu
# =============================================================================

set -euo pipefail

# ── Colors ────────────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
RESET='\033[0m'

# ── Helpers ───────────────────────────────────────────────────────────────────
info()    { echo -e "${BLUE}[INFO]${RESET}  $*"; }
success() { echo -e "${GREEN}[OK]${RESET}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${RESET}  $*"; }
error()   { echo -e "${RED}[ERROR]${RESET} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}${CYAN}▶ $*${RESET}"; }
divider() { echo -e "${CYAN}$(printf '─%.0s' {1..60})${RESET}"; }

# ── Configuration ─────────────────────────────────────────────────────────────
BINLOG_CNF="/etc/mysql/mariadb.conf.d/99-binlog.cnf"
BINLOG_DIR="/var/log/mysql"
BINLOG_PREFIX="mysql-bin"

# ── Banner ────────────────────────────────────────────────────────────────────
print_banner() {
    echo -e "${BOLD}${CYAN}"
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║         MariaDB Binary Log Setup                         ║"
    echo "║         Point-in-Time Recovery Configuration             ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo -e "${RESET}"
}

# ── Checks ────────────────────────────────────────────────────────────────────
check_root() {
    if [[ $EUID -ne 0 ]]; then
        error "This script must be run as root (sudo ./setup_binlog.sh)"
    fi
}

check_mariadb() {
    if ! command -v mariadb &>/dev/null; then
        error "MariaDB client not found. Is MariaDB installed?"
    fi

    if ! systemctl is-active --quiet mariadb; then
        error "MariaDB is not running. Start it first: systemctl start mariadb"
    fi

    success "MariaDB is running."
}

# ── Check if already enabled ──────────────────────────────────────────────────
check_already_enabled() {
    step "Checking current binary log status"

    BINLOG_STATUS=$(mariadb -N -B -e "SHOW VARIABLES LIKE 'log_bin'" | awk '{print $2}')

    if [[ "$BINLOG_STATUS" == "ON" ]]; then
        warn "Binary logging is already enabled."
        mariadb -e "SHOW VARIABLES LIKE 'log_bin%';"
        echo ""
        read -rp "$(echo -e ${YELLOW}Reconfigure anyway? [y/N]:${RESET} )" RECONF
        if [[ ! "$RECONF" =~ ^[yY]$ ]]; then
            info "No changes made."
            exit 0
        fi
    else
        info "Binary logging is currently disabled."
    fi
}

# ── Ensure log directory exists ───────────────────────────────────────────────
prepare_log_dir() {
    step "Preparing binary log directory"

    if [[ ! -d "$BINLOG_DIR" ]]; then
        info "Creating directory: ${BINLOG_DIR}..."
        mkdir -p "$BINLOG_DIR"
    fi

    chown mysql:mysql "$BINLOG_DIR"
    chmod 750 "$BINLOG_DIR"
    success "Directory ready: ${BINLOG_DIR}"
}

# ── Write config file ─────────────────────────────────────────────────────────
write_config() {
    step "Writing binary log configuration"

    if [[ -f "$BINLOG_CNF" ]]; then
        BACKUP_CNF="${BINLOG_CNF}.bak_$(date +%Y%m%d_%H%M%S)"
        warn "Existing config found – backing up to: ${BACKUP_CNF}"
        cp "$BINLOG_CNF" "$BACKUP_CNF"
    fi

    cat > "$BINLOG_CNF" << EOF
# =============================================================================
# ${BINLOG_CNF}
# MariaDB Binary Log configuration for Point-in-Time Recovery
# Generated by setup_binlog.sh on $(date)
# =============================================================================

[mysqld]

# Enable binary logging
log_bin                        = ${BINLOG_DIR}/${BINLOG_PREFIX}

# ROW format: logs actual data changes (safest for PITR)
binlog_format                  = ROW

# Auto-purge after 3 days (restic handles long-term retention)
expire_logs_days               = 3

# Sync every transaction to disk (no data loss on crash)
sync_binlog                    = 1

# InnoDB: flush log at every commit
innodb_flush_log_at_trx_commit = 1

# Max size per binary log file before rotation
max_binlog_size                = 100M

# Server ID (must be unique if using replication)
server_id                      = 1
EOF

    success "Config written to: ${BINLOG_CNF}"
}

# ── Restart MariaDB ───────────────────────────────────────────────────────────
restart_mariadb() {
    step "Restarting MariaDB"

    info "Restarting MariaDB to apply changes..."
    systemctl restart mariadb || error "MariaDB failed to restart – check: journalctl -xe"

    sleep 2
    systemctl is-active --quiet mariadb || error "MariaDB is not running after restart"

    success "MariaDB restarted successfully."
}

# ── Verify ────────────────────────────────────────────────────────────────────
verify_binlog() {
    step "Verifying binary log status"

    BINLOG_STATUS=$(mariadb -N -B -e "SHOW VARIABLES LIKE 'log_bin'" | awk '{print $2}')

    if [[ "$BINLOG_STATUS" != "ON" ]]; then
        error "Binary logging is still disabled after restart. Check: journalctl -xe"
    fi

    success "Binary logging is active!"
    echo ""
    mariadb -e "SHOW VARIABLES LIKE 'log_bin%';"
    echo ""
    mariadb -e "SHOW BINARY LOGS;"
}

# ── Summary ───────────────────────────────────────────────────────────────────
print_summary() {
    divider
    echo -e "\n${BOLD}${GREEN}✔ Binary log setup complete!${RESET}\n"

    echo -e "${BOLD}Configuration:${RESET}"
    echo -e "  Config file : ${BOLD}${BINLOG_CNF}${RESET}"
    echo -e "  Log dir     : ${BOLD}${BINLOG_DIR}${RESET}"
    echo -e "  Log prefix  : ${BOLD}${BINLOG_PREFIX}${RESET}"
    echo -e "  Format      : ${BOLD}ROW${RESET}"
    echo -e "  Retention   : ${BOLD}3 days${RESET}"
    echo ""
    echo -e "${BOLD}Next steps:${RESET}"
    echo -e "  1. Set up the binary log backup cronjob:"
    echo -e "     ${CYAN}0 */6 * * * /root/scripts/mariadb/mariadb_binlog_backup.sh >> /var/log/mariadb_binlog_backup.log 2>&1${RESET}"
    echo ""
    echo -e "  2. For Point-in-Time Recovery run:"
    echo -e "     ${CYAN}./mariadb_pitr_restore.sh \"YYYY-MM-DD HH:MM:SS\"${RESET}"
    echo ""
    divider
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
    print_banner
    check_root
    check_mariadb
    check_already_enabled
    prepare_log_dir
    write_config
    restart_mariadb
    verify_binlog
    print_summary
}

main "$@"
